# Generated by Django 5.0.2 on 2024-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LpMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tel_no', models.CharField(max_length=20)),
                ('url_store', models.URLField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('open_hours', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=255)),
                ('scrape_date', models.DateField()),
            ],
            options={
                'db_table': 'lp_master_tb',
            },
        ),
    ]
